package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"strconv"

	"github.com/tsbolty/GophersPlayground/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	userID, err := strconv.ParseUint(input.UserID, 10, 64)

	if err != nil {
		return nil, err
	}

	// On 32-bit systems, check for overflow
	if uint64(uint(userID)) != userID {
		// Handle the overflow, for example, return a GraphQL error
		return nil, fmt.Errorf("userID is too large for this platform")
	}

	todo, err := r.TodoService.CreateTodoForUser(input.Text, uint(userID))
	if err != nil {
		return nil, err
	}

	graphqlTodo := &model.Todo{
		ID:     fmt.Sprintf("%d", todo.ID),
		Text:   todo.Text,
		Done:   todo.Done,
		UserID: int(todo.UserID),
	}

	return graphqlTodo, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginUser) (*model.AuthPayload, error) {
	accessToken, refreshToken, user, err := r.AuthService.AuthenticateUser(input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to authenticate user")
	}

	return &model.AuthPayload{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		User: &model.User{
			ID:    fmt.Sprintf("%d", user.ID),
			Name:  user.Name,
			Email: user.Email,
		},
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.NewUser) (*model.AuthPayload, error) {
	accessToken, refreshToken, dbUser, err := r.AuthService.RegisterUser(input.Email, input.Name, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		User: &model.User{
			ID:    fmt.Sprintf("%d", dbUser.ID),
			Name:  dbUser.Name,
			Email: dbUser.Email,
		},
	}, nil
}

// FindAllUsers is the resolver for the findAllUsers field.
func (r *queryResolver) FindAllUsers(ctx context.Context) ([]*model.User, error) {
	dbUsers, err := r.UserBusinessService.FindAllUsers()
	if err != nil {
		return nil, err
	}

	graphqlUsers := make([]*model.User, len(dbUsers))

	for i, user := range dbUsers {
		graphqlUsers[i] = &model.User{
			ID:    fmt.Sprintf("%d", user.ID),
			Name:  user.Name,
			Email: user.Email,
		}
	}

	return graphqlUsers, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos, err := r.TodoBusinessService.GetAllTodos()

	if err != nil {
		return nil, err
	}

	graphqlTodos := make([]*model.Todo, len(todos))

	for i, todo := range todos {
		graphqlTodos[i] = &model.Todo{
			ID:     fmt.Sprintf("%d", todo.ID),
			Text:   todo.Text,
			Done:   todo.Done,
			UserID: int(todo.UserID),
		}
	}

	return graphqlTodos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	refreshTokenUint, err := strconv.ParseUint(refreshToken, 10, 64)
	if err != nil {
		return nil, err
	}

	accessToken, newRefreshToken, err := r.AuthService.GenerateNewTokens(uint(refreshTokenUint))
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  accessToken,
		RefreshToken: newRefreshToken,
	}, nil
}
func (r *mutationResolver) RefreshAccessToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	refreshTokenUint, err := strconv.ParseUint(refreshToken, 10, 64)
	if err != nil {
		return nil, err
	}

	accessToken, newRefreshToken, err := r.AuthService.GenerateNewTokens(uint(refreshTokenUint))
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  accessToken,
		RefreshToken: newRefreshToken,
	}, nil
}
