version: '3.8'

services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
      # - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
