version: '3.8'

services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 5s

volumes:
  postgres_data:
